import Head from "next/head";
import HomeContainer from "../features/Home/HomeContainer";

import { Test } from "../styles/test.styled";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Test>Hello</Test> */}
        <HomeContainer />
      </main>
    </div>
  );
}
